pipeline {
  
  
  agent { label 'ubuntu_micro'}
  
  tools {
          maven 'maven3'
          docker 'docker'
  }
  stages {
    stage ('checkout') {
      steps {
        git branch:'dev' url: 'https://github.com/govarthinisundararaj/Spring-Boot.git'
      }
    }
  stages {
    stage ('Build') {
      steps {
        sh 'mvn clean install'
      }
    } 
  stages {
    stage ('Docker_compose_up') {
      steps {
       sh 'docker-compose build'
       sh 'docker-compose up -d --abort-on-container-exit'
      }
    } 
  }
