pipeline {
  
  
  agent { label 'ubuntu_micro'}
  
  tools {
          maven 'maven3'
          docker 'docker'
  }
  stages {
    stage ('checkout') {
      steps {
        git url: 'https://github.com/govarthinisundararaj/springboothelloworldazure.git'
      }
    }
  stages {
    stage ('Build') {
      steps {
        
      }
    } 
  stages {
    stage ('Docker_compose_up') {
      steps {
        
      }
    } 
